version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    environment:
      - DATABASE_URL=postgresql://app:app@db:5432/app
      - DJANGO_DEBUG=1
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  pgdata:
